const APP_DATA = {
  usuarios: [
    { id: 'director',   nombre: 'Director General',     rol: 'director',   pin: '1111' },
    { id: 'produccion', nombre: 'Encargado Producción', rol: 'produccion', pin: '2222' },
    { id: 'logistica',  nombre: 'Logística',            rol: 'logistica',  pin: '3333' },
  ],

  // Estados posibles: 'en_proceso' | 'funda' | 'terminado'
  produccion: {
    '01/06': {
      AGUSTIN: [
        { oc: '3018', cliente: 'Liliana',        modelo: 'Bali',       valor: 2131687,  estado: 'terminado' },
        { oc: '',     cliente: 'Stock Tigre',     modelo: 'Bariloche',  valor: 3800000,  estado: 'terminado' },
        { oc: '3014', cliente: 'Elva Rios',       modelo: 'Paula',      valor: 1425416,  estado: 'terminado' },
        { oc: '3026', cliente: 'Miguez Analia',   modelo: 'Capri',      valor: 2700000,  estado: 'terminado' },
      ],
      FRANCIS: [
        { oc: '5423', cliente: 'Sanchez Martin',    modelo: 'Capri Cuero',  valor: 2600000,  estado: 'terminado' },
        { oc: '3001', cliente: 'Campeoto Julieta',  modelo: 'Capri',        valor: 2120000,  estado: 'terminado' },
        { oc: '3016', cliente: 'Barbara',           modelo: 'Linea Joven',  valor: 1978938,  estado: 'terminado' },
        { oc: '',     cliente: 'Stock Tigre',       modelo: 'Cubo',         valor: 1600000,  estado: 'terminado' },
        { oc: '5437', cliente: 'Tomas De Luca',     modelo: 'Bali',         valor: 0,        estado: 'terminado' },
      ],
      LUIS: [
        { oc: '3021', cliente: 'Donofrio',       modelo: 'Leon Retap.',    valor: 680000,   estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Leon Retap.',    valor: 2098872,  estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Leon Corderoy',  valor: 1998926,  estado: 'terminado' },
        { oc: '3027', cliente: 'Gastaldo Gabriel',modelo: 'Bali',           valor: 0,        estado: 'terminado' },
      ],
      NICOLAS: [
        { oc: '3021', cliente: 'Donofrio',         modelo: 'Leon Retap.',   valor: 0,        estado: 'terminado' },
        { oc: '3013', cliente: 'Carvallo Matias',  modelo: 'Capri',         valor: 0,        estado: 'terminado' },
        { oc: '3001', cliente: 'Campeoto Julieta', modelo: 'Capri',         valor: 0,        estado: 'terminado' },
        { oc: '5423', cliente: 'Sanchez Martin',   modelo: 'Capri Cuero',   valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter',  modelo: 'Leon Retap.',   valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter',  modelo: 'Leon Corderoy', valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Marion',           modelo: 'Colchonetas x2',valor: 360000,   estado: 'terminado' },
        { oc: '3026', cliente: 'Miguez Analia',    modelo: 'Capri',         valor: 0,        estado: 'terminado' },
        { oc: '2990', cliente: 'Lazarus Martin 2', modelo: 'Bali',          valor: 2139009,  estado: 'terminado' },
      ],
    },

    '08/06': {
      AGUSTIN: [
        { oc: '3019', cliente: 'Gimena Arq',        modelo: 'Leon',          valor: 4660000,  estado: 'terminado' },
        { oc: '3009', cliente: 'Arriggi Felicitas',  modelo: 'Personalizado', valor: 7700000,  estado: 'terminado' },
        { oc: '',     cliente: 'Isra Eduardo/Liliana',modelo: 'Leon con Vivo', valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter',    modelo: 'Puff',          valor: 335160,   estado: 'terminado' },
        { oc: '3012', cliente: 'Loigioia Edgardo',   modelo: 'Leon',          valor: 1890000,  estado: 'terminado' },
      ],
      FRANCIS: [
        { oc: '3013', cliente: 'Carballo Matias',    modelo: 'Capri',         valor: 2393820,  estado: 'terminado' },
        { oc: '3000', cliente: 'Vk Home',            modelo: 'Puff',          valor: 1200000,  estado: 'terminado' },
        { oc: '3023', cliente: 'Soria Liliana',      modelo: 'Bali',          valor: 2398140,  estado: 'terminado' },
        { oc: '3019', cliente: 'Gimena Arq',         modelo: 'Leon',          valor: 0,        estado: 'terminado' },
        { oc: '3009', cliente: 'Arriggi Felicitas',  modelo: 'Personalizado', valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Isra Eduardo/Liliana',modelo: 'Leon con Vivo', valor: 2106720,  estado: 'terminado' },
        { oc: '3031', cliente: 'Biagosch Rosa',      modelo: 'Linea Joven Esq.',valor: 0,      estado: 'terminado' },
      ],
      LUIS: [
        { oc: '3022', cliente: 'Mapoteca',           modelo: 'Capri Butacon', valor: 709000,   estado: 'terminado' },
        { oc: '3019', cliente: 'Gimena Arq',         modelo: 'Leon',          valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter',    modelo: 'Capri',         valor: 2018966,  estado: 'terminado' },
        { oc: '3009', cliente: 'Arriggi Felicitas',  modelo: 'Personalizado', valor: 0,        estado: 'terminado' },
      ],
      NICOLAS: [
        { oc: '',     cliente: 'Isra Eduardo/Liliana',modelo: 'Leon con Vivo', valor: 0,       estado: 'terminado' },
        { oc: '3019', cliente: 'Gimena Arq',          modelo: 'Leon',          valor: 0,       estado: 'terminado' },
        { oc: '3009', cliente: 'Arriggi Felicitas',   modelo: 'Personalizado', valor: 0,       estado: 'terminado' },
        { oc: '3022', cliente: 'Mapoteca',            modelo: 'Capri Butacon', valor: 0,       estado: 'terminado' },
        { oc: '3017', cliente: 'Ramiro',              modelo: 'Capri',         valor: 0,       estado: 'terminado' },
      ],
    },

    '15/06': {
      AGUSTIN: [
        { oc: '5455', cliente: 'Josefina Ch', modelo: 'Personalizado', valor: 3280000, estado: 'terminado' },
        { oc: '',     cliente: 'Paula Pls',   modelo: 'Respaldo',       valor: 2882000, estado: 'terminado' },
      ],
      FRANCIS: [
        { oc: '2820', cliente: 'Bazan Mariza',   modelo: 'Orbed',            valor: 0,        estado: 'terminado' },
        { oc: '3031', cliente: 'Biagosch Rosa',  modelo: 'Linea Joven Esq.', valor: 3777970,  estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Calipso',          valor: 2634000,  estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Puff Capri',       valor: 443300,   estado: 'terminado' },
      ],
      LUIS: [
        { oc: '2820', cliente: 'Bazan Mariza',   modelo: 'Capri',  valor: 0,        estado: 'terminado' },
        { oc: '5457', cliente: 'Chavez Fidel',   modelo: 'Capri',  valor: 2180000,  estado: 'terminado' },
        { oc: '3017', cliente: 'Ramiro',         modelo: 'Capri',  valor: 2321810,  estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter',modelo: 'Capri',  valor: 2321810,  estado: 'terminado' },
        { oc: '3028', cliente: 'Dato Patricio',  modelo: 'Puff Leon',valor: 438900, estado: 'terminado' },
      ],
      NICOLAS: [
        { oc: '5437', cliente: 'Tomas De Luca',  modelo: 'Bali',             valor: 2595550,  estado: 'terminado' },
        { oc: '3027', cliente: 'Gastaldo Gabriel',modelo: 'Bali',            valor: 2548776,  estado: 'terminado' },
        { oc: '2820', cliente: 'Bazan Mariza',   modelo: 'Capri',            valor: 0,        estado: 'terminado' },
        { oc: '5457', cliente: 'Chavez Fidel',   modelo: 'Capri',            valor: 0,        estado: 'terminado' },
        { oc: '3017', cliente: 'Ramiro',         modelo: 'Capri',            valor: 0,        estado: 'terminado' },
        { oc: '3031', cliente: 'Biagosch Rosa',  modelo: 'Linea Joven Esq.', valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Stock Norcenter',modelo: 'Calipso',          valor: 0,        estado: 'terminado' },
        { oc: '2820', cliente: 'Bazan Mariza',   modelo: 'Orbed',            valor: 0,        estado: 'terminado' },
        { oc: '',     cliente: 'Paula Pls',      modelo: 'Respaldo',         valor: 0,        estado: 'terminado' },
      ],
    },

    '22/06': {
      AGUSTIN: [
        { oc: '',     cliente: 'Chaves Matilde',  modelo: 'Bariloche',  valor: 1799034, estado: 'en_proceso' },
        { oc: '3036', cliente: 'Vaguedes Andres', modelo: 'Sofa Luca',  valor: 882000,  estado: 'en_proceso' },
        { oc: '',     cliente: 'Paula Pls n2',    modelo: 'Sandro',     valor: 2000000, estado: 'en_proceso' },
        { oc: '3049', cliente: 'Matas Miguel',    modelo: 'Bali',       valor: 1873000, estado: 'en_proceso' },
      ],
      FRANCIS: [
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Paula',        valor: 1872200, estado: 'en_proceso' },
        { oc: '2820', cliente: 'Bazan Mariza',    modelo: 'Orbed',        valor: 1600000, estado: 'en_proceso' },
        { oc: '3008', cliente: 'Vittu Papini',    modelo: 'Orbed',        valor: 1820000, estado: 'en_proceso' },
        { oc: '',     cliente: 'Paula Pls n1',    modelo: 'Sandro',       valor: 2549000, estado: 'en_proceso' },
        { oc: '',     cliente: 'Isra Liliana',    modelo: 'Leon con Vivo',valor: 0,       estado: 'en_proceso' },
        { oc: '6044', cliente: 'Pierreti Martin', modelo: 'Capri',        valor: 0,       estado: 'en_proceso' },
        { oc: '3046', cliente: 'Blas Silvia',     modelo: 'Linea Joven',  valor: 1978939, estado: 'en_proceso' },
      ],
      LUIS: [
        { oc: '2820', cliente: 'Bazan Mariza',    modelo: 'Capri',         valor: 1600000, estado: 'en_proceso' },
        { oc: '6044', cliente: 'Pierreti Martin', modelo: 'Capri',         valor: 1773200, estado: 'en_proceso' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Capri',         valor: 1950520, estado: 'en_proceso' },
        { oc: '',     cliente: 'Isra Liliana',    modelo: 'Leon con Vivo', valor: 2106720, estado: 'en_proceso' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Leon con Vivo', valor: 2633400, estado: 'en_proceso' },
      ],
      NICOLAS: [
        { oc: '',     cliente: 'Isra Liliana',    modelo: 'Leon con Vivo', valor: 0,       estado: 'en_proceso' },
        { oc: '',     cliente: 'Stock Norcenter', modelo: 'Leon con Vivo', valor: 0,       estado: 'en_proceso' },
        { oc: '6044', cliente: 'Pierreti Martin', modelo: 'Capri',         valor: 0,       estado: 'en_proceso' },
      ],
    },
  },

  tareas: [
    { id: 1, fecha: '26/06', horario: 'Mediodía',        tarea: 'Retirar efectivo Local Norcenter',             direccion: '',                                                                              contacto: '-',            observacion: '$146.000', hecho: false },
    { id: 2, fecha: '26/06', horario: 'Entre 10 y 12hs', tarea: 'Llevar sillón a Liliana',                      direccion: 'República de la India 3089, Piso 10',                                           contacto: '115719-0759',  observacion: '',         hecho: false },
    { id: 3, fecha: '26/06', horario: '11 a 12hs',       tarea: 'Levantar a Yamir en Capital',                  direccion: 'Tiene que hacer un trámite en Capital, que vayan hablando y lo levante Guillermo', contacto: '11 7165-6660', observacion: '',         hecho: false },
    { id: 4, fecha: '26/06', horario: 'Llamar antes',    tarea: 'Buscar muestrario Candy (Bruno Camila)',        direccion: 'Carlos Gardel 1777, Olivos',                                                    contacto: '115893-2068',  observacion: '',         hecho: false },
    { id: 5, fecha: '26/06', horario: 'Durante el día',  tarea: 'Llevar sierra sin fin a Afiladora',            direccion: '',                                                                              contacto: '',             observacion: '',         hecho: false },
    { id: 6, fecha: '26/06', horario: 'Durante el día',  tarea: 'Comprar 25 resortes de 4 vueltas (Daniel)',    direccion: '',                                                                              contacto: '',             observacion: 'Alplast / Dist. San Fer.', hecho: false },
    { id: 7, fecha: '26/06', horario: 'Durante el día',  tarea: 'Buscar tele en Rocha',                         direccion: '',                                                                              contacto: '',             observacion: '',         hecho: false },
    { id: 8, fecha: '26/06', horario: 'Durante el día',  tarea: 'Comprar lijas para lijadora, papel higiénico, cierres (muestras en oficina)', direccion: '', contacto: '', observacion: '', hecho: false },
  ],

  telas: [
    { orden: '5423', cliente: 'SANCHEZ MARTIN', tela: 'CUERO VACUNO VARESE HABANO', metros: '25', prov: 'CUEROS LANUS', pedido: false, llego: true, noStock: false },
    { orden: '5425', cliente: 'DJIVELEKIAN JUAN', tela: 'PANA TIGER PIEDRA', metros: '15', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5426', cliente: 'VALLEJOS NICOLAS', tela: 'PANA PANE VERDE INGLES', metros: '12', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '2978', cliente: 'BASCOY MARTINA', tela: 'CORDEROY VERDE', metros: '10', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '5436', cliente: 'SANTIAGO CHAO', tela: 'PANA MILANO CHARCOAL', metros: '14', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '2985', cliente: 'DE PAOLI CLAUDIA', tela: 'PANA MILANO BONE', metros: '6', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5435', cliente: 'MIGOYA MARIA MARTA', tela: 'PANA MILANO BEIGE OSCURO', metros: '20', prov: 'ETAMINE', pedido: false, llego: false, noStock: false },
    { orden: '5433', cliente: 'LAZARUS MARTIN', tela: 'TUSSOR AQUA', metros: '11', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5433', cliente: 'LAZARUS MARTIN', tela: 'TUSSOR OCEANO', metros: '2', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5432', cliente: 'LAZARUS MARTIN', tela: 'TUSSOR HUESO', metros: '2', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5434', cliente: 'LAZARUS MARTIN', tela: 'TUSSOR VISON', metros: '8', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5434', cliente: 'LAZARUS MARTIN', tela: 'TUSSOR NIEBLA', metros: '4', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5430', cliente: 'SANCHEZ EMILIANO', tela: 'PANA PANE ROSA', metros: '70 cm', prov: 'ALPLAST', pedido: false, llego: true, noStock: false },
    { orden: '2992', cliente: 'CABARITTI DAIANA', tela: 'PANA PANE #29 JADE', metros: '28', prov: 'ALPLAST', pedido: false, llego: true, noStock: false },
    { orden: '5431', cliente: 'VICTORICA GONZALEZ LOLA', tela: 'POLAR BEAR 2', metros: '10', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'RESPALDO PAULA', tela: 'PANA MILANO BEIGE OSCURO', metros: '8', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5438', cliente: 'CAMPEOTTO JULIETA', tela: 'CORDEROY 02 BEIGE', metros: '13', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '3005', cliente: 'VICCHI LUCHO', tela: 'EUROPA 10', metros: '14', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3007', cliente: 'HEBRERO DAMIAN', tela: 'PANA MILANO COCO', metros: '20', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '2973', cliente: 'VALLEJOS SOLEDAD', tela: 'TIGER 1', metros: '6', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '2973', cliente: 'VALLEJOS SOLEDAD', tela: 'TIGER 2 PIEDRA', metros: '2,5', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3006', cliente: 'LONGUEIRA VICKY', tela: 'TOUCH BEIGE 904', metros: '16', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5429', cliente: 'CANIGGIA JULIETA', tela: 'TUSSOR GRIS TOPO', metros: '17', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5447', cliente: 'DONOFRIO RETAPIZADO', tela: 'CANDY O7', metros: '14', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5443', cliente: 'BARBARA', tela: 'PANA PANNE VERDE INGLES 16', metros: '14', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5444', cliente: 'RAMIRO', tela: 'CORDEROY ROBLE 12', metros: '15', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '5442', cliente: 'ELVA RIOS', tela: 'TUSOR GRIS TOPO', metros: '15', prov: 'LULA', pedido: false, llego: true, noStock: false },
    { orden: '5441', cliente: 'CARBALLO MATIAS', tela: 'CORDEROY GRIS 10', metros: '22', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '5445', cliente: 'LILIANA', tela: 'PANA TOUCH VISON', metros: '14', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5440', cliente: 'LOGIOIA EDGARDO', tela: 'CANDY S6', metros: '13', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3019', cliente: 'GIMENA ARQ', tela: 'CANDY S2', metros: '30', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5446', cliente: 'EDUARDO ISRA', tela: 'GUER 02', metros: '15', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3009', cliente: 'FELICITAS ARRIGI', tela: 'GUER A1', metros: '54', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3009', cliente: 'FELICITAS ARRIGI', tela: 'GUER GRIS', metros: '27', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3009', cliente: 'FELICITAS ARRIGI', tela: 'TERCIOPELO NEGRO', metros: '4', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5452', cliente: 'MIGUEZ ANALIA', tela: 'CORDEROY BEIGE 02', metros: '20', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '5455', cliente: 'CHIAPETTA JOSEFINA', tela: 'FLAX NATURAL', metros: '18', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5456', cliente: 'CHAVEZ MATILDE', tela: 'TOUCH TOMATE', metros: '17', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5457', cliente: 'CHAVEZS FIDEL', tela: 'CORDEROY VERDE 07', metros: '16', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '5448', cliente: 'MAPOTECA', tela: 'CORDEROY NATURAL 01', metros: '4', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '5449', cliente: 'SORIA LILIANA', tela: 'PANA TOUCH VISON', metros: '20', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5453', cliente: 'BIAGOSCH ROSA', tela: 'POLAR BEAR 02', metros: '20', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER', tela: 'CORDEROY GRIS 10', metros: '6', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER', tela: 'CORDEROY BEIGE 02', metros: '4', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER', tela: 'CORDEROY PLATA', metros: '9', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'JOANE', tela: 'FLAX NEVADO', metros: '15', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER', tela: 'CORDEROY VERDE ROLLO', metros: '', prov: 'SIROTA', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER CALIPSO ESQ.', tela: 'CANDY O5', metros: '18', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER LEON CON VIVO', tela: 'CANDY S2', metros: '17', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'STOCK NORCENTER LEON CON VIVO', tela: 'PANA MILANO BLACK', metros: '4', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5446', cliente: 'EDUARDO ISRA / LILIANA', tela: 'CANDY S2', metros: '16', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '3050', cliente: 'MATTIO CAMILA', tela: 'PANA MILANO PIEDRA', metros: '20', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5462', cliente: 'MATAS MIGUEL', tela: 'TUSSOR NIEBLA', metros: '13', prov: 'LULA', pedido: true, llego: false, noStock: false },
    { orden: '3008', cliente: 'PAPINI VITTU', tela: 'TEJIDO RAYA FONDO VISON 2', metros: '2', prov: 'LULA', pedido: true, llego: false, noStock: false },
    { orden: '3008', cliente: 'PAPINI VITTU', tela: 'TEJIDO BANDA FONDO GRIS', metros: '2', prov: 'LULA', pedido: true, llego: false, noStock: false },
    { orden: '5460', cliente: 'BLAS SILVIA', tela: 'EUROPA #9', metros: '14', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5459', cliente: 'DI CORLETO JULIETA', tela: 'PANA PANNE SECO 19-2541-23', metros: '14', prov: 'ALPLAST', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'PAULA PLS', tela: 'WATERFALL #3', metros: '12', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'PAULA PLS', tela: 'WATERFALL #5', metros: '2', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'PAULA PLS', tela: 'PANA PANE BEIGE', metros: '16', prov: 'ALPLAST', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'PAULA PLS', tela: 'PANA PANE CRUDO', metros: '16', prov: 'ALPLAST', pedido: false, llego: true, noStock: false },
    { orden: '5458', cliente: 'VAGEDES ANDRES', tela: 'TOUCH CEMENTO 903', metros: '4', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '5463', cliente: 'FERRARO MARIA', tela: 'GUER 2', metros: '13', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '', cliente: 'SOFA FLORENCIA STOCK', tela: 'PANA OPAL 301', metros: '15', prov: 'ETAMINE', pedido: false, llego: true, noStock: false },
    { orden: '6002', cliente: 'PRUEBA', tela: 'PANA MILANO', metros: '10', prov: 'ETAMINE', pedido: false, llego: false, noStock: false }
  ]
};